@extends('layouts.agent')
@section('title', 'Agent Dashboard')
@section('page-title', 'Dashboard')
@section('content')
<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
    <div class="bg-white rounded-xl shadow-card p-6"><div class="flex items-center justify-between"><div><p class="text-sm font-medium text-gray-500">Total Sales</p><p class="text-2xl font-bold text-gray-900">Rs. {{ number_format($totalSales??0,2) }}</p></div><div class="w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center"><i class="fas fa-shopping-cart text-blue-600 text-xl"></i></div></div></div>
    <div class="bg-white rounded-xl shadow-card p-6"><div class="flex items-center justify-between"><div><p class="text-sm font-medium text-gray-500">Commission Earned</p><p class="text-2xl font-bold text-purple-600">Rs. {{ number_format($totalCommission??0,2) }}</p></div><div class="w-12 h-12 bg-purple-100 rounded-xl flex items-center justify-center"><i class="fas fa-coins text-purple-600 text-xl"></i></div></div></div>
    <div class="bg-white rounded-xl shadow-card p-6"><div class="flex items-center justify-between"><div><p class="text-sm font-medium text-gray-500">Recovery Rate</p><p class="text-2xl font-bold {{ ($recoveryRate??0) >= 95 ? 'text-green-600' : 'text-yellow-600' }}">{{ number_format($recoveryRate??0,2) }}%</p></div><div class="w-12 h-12 bg-green-100 rounded-xl flex items-center justify-center"><i class="fas fa-percentage text-green-600 text-xl"></i></div></div></div>
    <div class="bg-white rounded-xl shadow-card p-6"><div class="flex items-center justify-between"><div><p class="text-sm font-medium text-gray-500">New Customers</p><p class="text-2xl font-bold text-orange-600">{{ $newCustomers??0 }}</p></div><div class="w-12 h-12 bg-orange-100 rounded-xl flex items-center justify-center"><i class="fas fa-user-plus text-orange-600 text-xl"></i></div></div></div>
</div>
<div class="grid grid-cols-1 sm:grid-cols-3 gap-6 mt-6">
    <a href="{{ route('agent.sales.create') }}" class="bg-gradient-to-r from-blue-600 to-blue-700 rounded-xl shadow-lg p-6 text-white hover:shadow-xl"><div class="flex items-center"><div class="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center"><i class="fas fa-plus text-2xl"></i></div><div class="ml-4"><h3 class="text-lg font-semibold">New Sale</h3><p class="text-blue-100 text-sm">Create invoice</p></div></div></a>
    <a href="{{ route('agent.customers.create') }}" class="bg-gradient-to-r from-green-600 to-green-700 rounded-xl shadow-lg p-6 text-white hover:shadow-xl"><div class="flex items-center"><div class="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center"><i class="fas fa-user-plus text-2xl"></i></div><div class="ml-4"><h3 class="text-lg font-semibold">New Customer</h3><p class="text-green-100 text-sm">Add customer</p></div></div></a>
    <a href="{{ route('agent.commissions.index') }}" class="bg-gradient-to-r from-purple-600 to-purple-700 rounded-xl shadow-lg p-6 text-white hover:shadow-xl"><div class="flex items-center"><div class="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center"><i class="fas fa-coins text-2xl"></i></div><div class="ml-4"><h3 class="text-lg font-semibold">Commission</h3><p class="text-purple-100 text-sm">View earnings</p></div></div></a>
</div>
<div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-6">
    <div class="bg-white rounded-xl shadow-card overflow-hidden"><div class="px-6 py-4 border-b border-gray-200"><h4 class="text-lg font-semibold text-gray-900"><i class="fas fa-clock text-gray-400 mr-2"></i> Recent Sales</h4></div><div class="p-4">@if(isset($sales) && $sales->count()>0) @foreach($sales->take(5) as $sale)<div class="border-b border-gray-100 py-2 last:border-0 flex justify-between"><div><a href="{{ route('agent.sales.show',$sale) }}" class="text-blue-600 hover:underline text-sm font-medium">{{ $sale->invoice_no }}</a><p class="text-xs text-gray-500">{{ $sale->customer->name??'N/A' }}</p></div><div class="text-right"><p class="text-sm font-semibold">Rs. {{ number_format($sale->total_amount,2) }}</p><span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium {{ $sale->status_color }}">{{ $sale->status_label }}</span></div></div>@endforeach @else <p class="text-center text-gray-500 py-4">No sales yet.</p> @endif</div></div>
    <div class="bg-white rounded-xl shadow-card overflow-hidden"><div class="px-6 py-4 border-b border-gray-200"><h4 class="text-lg font-semibold text-gray-900"><i class="fas fa-coins text-gray-400 mr-2"></i> Recent Commissions</h4></div><div class="p-4">@if(isset($commissionLogs) && $commissionLogs->count()>0) @foreach($commissionLogs as $log)<div class="border-b border-gray-100 py-2 last:border-0 flex justify-between"><div><p class="text-sm font-medium text-gray-900">{{ $log->type_label }}</p><p class="text-xs text-gray-500">{{ $log->created_at->format('d-m-Y H:i') }}</p></div><div class="text-right"><p class="text-sm font-semibold text-purple-600">+ Rs. {{ number_format($log->amount,2) }}</p><span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium {{ $log->is_paid ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800' }}">{{ $log->is_paid ? 'Paid' : 'Pending' }}</span></div></div>@endforeach @else <p class="text-center text-gray-500 py-4">No commissions yet.</p> @endif</div></div>
</div>
@endsection